services:
  postgres:
    image: postgres:17
    container_name: accidents-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  importador:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: accidents-importador
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ConnectionStringParam=Host=postgres;Port=5432;Username=postgres;Password=123456;Database=victimes

volumes:
  postgres-data:
